<?php

namespace AppBundle\Entity\Customer\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CustomerNotificationSettingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerNotificationSettingRepository extends EntityRepository
{
}
