# app/config/common/services.yml
services:
    # Twig

    app.twig_extension:
        class:  AppBundle\Twig\AppExtension
        public: false
        tags:
            - { name: twig.extension }

    app.website_metadata_extension:
        class:  AppBundle\Twig\WebsiteMetadataExtension
        calls:
             - [setRequestStack, [ "@request_stack" ]]
             - [setManager, [ "@doctrine.orm.entity_manager" ]]
        public: false
        tags:
            - { name: twig.extension }

    # Event listeners

    app.listener.sync.authentication:
        class: AppBundle\EventListener\Sync\SyncAuthenticationListener
        calls:
            - [setManager, [ "@doctrine.orm.entity_manager" ]]
            - [setAuthentication, [ "@app.sync.security.authentication" ]]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

    app.exception_listener.sync:
        class: AppBundle\EventListener\Exception\SyncListener
        calls:
            - [setLogger, [ "@monolog.logger.sync" ]]
        tags:
            - { name: kernel.event_listener, event: kernel.exception, channel: sync }

    app.exception_listener.report:
        class: AppBundle\EventListener\Exception\ReportListener
        calls:
            - [setLogger, [ "@monolog.logger.report" ]]
        tags:
            - { name: kernel.event_listener, event: console.exception, channel: report }

    app.exception_listener.notification:
        class: AppBundle\EventListener\Exception\NotificationListener
        calls:
            - [setLogger, [ "@monolog.logger.report" ]]
        tags:
            - { name: kernel.event_listener, event: console.exception, channel: notification }

    app.listener.notification.post_vending_machines_purchases:
        class: AppBundle\EventListener\Notification\PostVendingMachinesPurchasesListener
        calls:
            - [setNotificationManager, [ "@app.notification.manager" ]]
            - [setNotificationSender, [ "@app.notification.sender" ]]
        tags:
            - { name: kernel.event_listener, event: app.event.post_vending_machines_purchases.after, method: processNotifications }

    app.listener.fallback.ie:
        class: AppBundle\EventListener\Fallback\IeFallbackListener
        calls:
            - [setIeFallbackController, [ "@app.ie_fallback_controller" ]]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    # Controller

    app.ie_fallback_controller:
        class: AppBundle\Controller\Website\IeFallbackController
        calls:
            - [setTemplating, [ "@templating" ]]

    # Database

    app.repository.global:
        class: AppBundle\Service\Repository\GlobalRepository
        calls:
            - [setConnection, [ "@database_connection" ]]

    # Notification

    app.notification.uni_sender.wrapper:
        class: AppBundle\Service\Notification\UniSender\UniSenderApiWrapper
        arguments:
            - "%uni_sender.key%"

    app.notification.manager:
        class: AppBundle\Service\Notification\NotificationManager
        calls:
            - [setManager, [ "@doctrine.orm.entity_manager" ]]
            - [setNotificationBuilder, [ "@app.notification.builder" ]]
            - [setNotificationSender, [ "@app.notification.sender" ]]
            - [setPurchaseServiceManager, [ "@app.purchase_service.manager" ]]

    app.notification.builder:
        class: AppBundle\Service\Notification\NotificationBuilder
        calls:
            - [setTranslator, [ "@translator" ]]

    app.notification.sender:
        class: AppBundle\Service\Notification\NotificationSender
        calls:
            - [setTranslator, [ "@translator" ]]
            - [setPhoneParameters, [ "%phones%" ]]
            - [setEmailParameters, [ "%emails%" ]]
            - [setUniSenderApiWrapper, [ "@app.notification.uni_sender.wrapper" ]]
            - [setMailerShortcut, [ "@app.common.mailer_shortcut" ]]

    # Payment

    app.payment.receipt.storage:
        class: AppBundle\Service\Payment\PaymentReceiptStorage
        calls:
            - [setRedis, [ "@snc_redis.default" ]]
            - [setSecurityContext, [ "@security.context" ]]

    app.payment.receipt.parser:
        class: AppBundle\Service\Payment\PaymentReceiptParser

    app.payment.receipt.validator:
        class: AppBundle\Service\Payment\PaymentReceiptValidator
        calls:
            - [setValidator, [ "@validator" ]]
            - [setManager, [ "@doctrine.orm.entity_manager" ]]

    app.payment.receipt.manager:
        class: AppBundle\Service\Payment\PaymentReceiptManager
        calls:
            - [setManager, [ "@doctrine.orm.entity_manager" ]]

    app.payment.liq_pay:
        class: LiqPay
        arguments:
            - "%liq_pay.key.public%"
            - "%liq_pay.key.private%"

    app.payment.liq_pay.manager:
        class: AppBundle\Service\Payment\PaymentLiqPayManager
        calls:
            - [setRouter, ["@router"]]
            - [setLiqPay, ["@app.payment.liq_pay"]]
            - [setLiqPayKeys, ["%liq_pay.key.public%", "%liq_pay.key.private%"]]

    # Purchase

    app.purchase_service.manager:
        class: AppBundle\Service\PurchaseService\PurchaseServiceManager
        calls:
            - [setManager, [ "@doctrine.orm.entity_manager" ]]
            - [setTranslator, [ "@translator" ]]

    # Common

    app.common.breadcrumbs:
        class: AppBundle\Service\Common\Breadcrumbs
        calls:
            - [setRouter, [ "@router" ]]
            - [setTranslator, [ "@translator" ]]

    app.common.messages:
        class: AppBundle\Service\Common\Messages
        calls:
            - [setSession, [ "@session" ]]
            - [setTranslator, [ "@translator" ]]

    app.common.mailer_shortcut:
        class: AppBundle\Service\Common\MailerShortcut
        calls:
            - [setMailer, [ "@mailer" ]]

    # Validators

    app.validator.uploaded_product_image:
        class: AppBundle\Service\Validator\UploadedProductImageValidator
        calls:
            - [setValidator, [ "@validator" ]]
            - [setTranslator, [ "@translator" ]]

    app.validator.uploaded_supplier_image:
        class: AppBundle\Service\Validator\UploadedSupplierImageValidator
        calls:
            - [setValidator, [ "@validator" ]]
            - [setTranslator, [ "@translator" ]]

    # Security voters

    app.security.role_hierarchy:
        alias: security.role_hierarchy

    app.voter_setting:
        class:  AppBundle\Security\Authorization\Voter\SettingVoter
        public: false
        calls:
            - [setRoleHierarchy, [ "@app.security.role_hierarchy" ]]
        tags:
            - { name: security.voter }

    app.voter_employee:
        class:  AppBundle\Security\Authorization\Voter\EmployeeVoter
        public: false
        calls:
            - [setRoleHierarchy, [ "@app.security.role_hierarchy" ]]
        tags:
            - { name: security.voter }

    app.voter_region:
        class:  AppBundle\Security\Authorization\Voter\RegionVoter
        public: false
        calls:
            - [setRoleHierarchy, [ "@app.security.role_hierarchy" ]]
        tags:
            - { name: security.voter }

    app.voter_settlement:
        class:  AppBundle\Security\Authorization\Voter\SettlementVoter
        public: false
        calls:
            - [setRoleHierarchy, [ "@app.security.role_hierarchy" ]]
        tags:
            - { name: security.voter }

    app.voter_school:
        class:  AppBundle\Security\Authorization\Voter\SchoolVoter
        public: false
        calls:
            - [setRoleHierarchy, [ "@app.security.role_hierarchy" ]]
        tags:
            - { name: security.voter }

    app.voter_vending_machine:
        class:  AppBundle\Security\Authorization\Voter\VendingMachineVoter
        public: false
        calls:
            - [setRoleHierarchy, [ "@app.security.role_hierarchy" ]]
        tags:
            - { name: security.voter }

    app.voter_nfc_tag:
        class:  AppBundle\Security\Authorization\Voter\NfcTagVoter
        public: false
        calls:
            - [setRoleHierarchy, [ "@app.security.role_hierarchy" ]]
        tags:
            - { name: security.voter }

    app.voter_supplier:
        class:  AppBundle\Security\Authorization\Voter\SupplierVoter
        public: false
        calls:
            - [setRoleHierarchy, [ "@app.security.role_hierarchy" ]]
        tags:
            - { name: security.voter }

    app.voter_product:
        class:  AppBundle\Security\Authorization\Voter\ProductVoter
        public: false
        calls:
            - [setRoleHierarchy, [ "@app.security.role_hierarchy" ]]
        tags:
            - { name: security.voter }

    app.voter_product_vending_group:
        class:  AppBundle\Security\Authorization\Voter\ProductVendingGroupVoter
        public: false
        calls:
            - [setRoleHierarchy, [ "@app.security.role_hierarchy" ]]
        tags:
            - { name: security.voter }

    app.voter_customer:
        class:  AppBundle\Security\Authorization\Voter\CustomerVoter
        public: false
        calls:
            - [setRoleHierarchy, [ "@app.security.role_hierarchy" ]]
        tags:
            - { name: security.voter }

    app.voter_student:
        class:  AppBundle\Security\Authorization\Voter\StudentVoter
        public: false
        calls:
            - [setRoleHierarchy, [ "@app.security.role_hierarchy" ]]
        tags:
            - { name: security.voter }

    app.voter_purchase:
        class:  AppBundle\Security\Authorization\Voter\PurchaseVoter
        public: false
        calls:
            - [setRoleHierarchy, [ "@app.security.role_hierarchy" ]]
        tags:
            - { name: security.voter }

    app.voter_purchase_service:
        class:  AppBundle\Security\Authorization\Voter\PurchaseServiceVoter
        public: false
        calls:
            - [setRoleHierarchy, [ "@app.security.role_hierarchy" ]]
        tags:
            - { name: security.voter }

    app.voter_payment_receipt:
        class:  AppBundle\Security\Authorization\Voter\PaymentReceiptVoter
        public: false
        calls:
            - [setRoleHierarchy, [ "@app.security.role_hierarchy" ]]
        tags:
            - { name: security.voter }

    # Security services

    app.security.setting_boundless_access:
        class: AppBundle\Service\Security\SettingBoundlessAccess
        calls:
            - [setAuthorizationChecker, [ "@security.authorization_checker" ]]

    app.security.employee_boundless_access:
        class: AppBundle\Service\Security\EmployeeBoundlessAccess
        calls:
            - [setAuthorizationChecker, [ "@security.authorization_checker" ]]

    app.security.region_boundless_access:
        class: AppBundle\Service\Security\RegionBoundlessAccess
        calls:
            - [setAuthorizationChecker, [ "@security.authorization_checker" ]]

    app.security.settlement_boundless_access:
        class: AppBundle\Service\Security\SettlementBoundlessAccess
        calls:
            - [setAuthorizationChecker, [ "@security.authorization_checker" ]]

    app.security.school_boundless_access:
        class: AppBundle\Service\Security\SchoolBoundlessAccess
        calls:
            - [setAuthorizationChecker, [ "@security.authorization_checker" ]]

    app.security.vending_machine_boundless_access:
        class: AppBundle\Service\Security\VendingMachineBoundlessAccess
        calls:
            - [setAuthorizationChecker, [ "@security.authorization_checker" ]]

    app.security.vending_machine_event_boundless_access:
        class: AppBundle\Service\Security\VendingMachineEventBoundlessAccess
        calls:
            - [setAuthorizationChecker, [ "@security.authorization_checker" ]]

    app.security.vending_machine_load_boundless_access:
        class: AppBundle\Service\Security\VendingMachineLoadBoundlessAccess
        calls:
            - [setAuthorizationChecker, [ "@security.authorization_checker" ]]

    app.security.nfc_tag_boundless_access:
        class: AppBundle\Service\Security\NfcTagBoundlessAccess
        calls:
            - [setAuthorizationChecker, [ "@security.authorization_checker" ]]

    app.security.supplier_boundless_access:
        class: AppBundle\Service\Security\SupplierBoundlessAccess
        calls:
            - [setAuthorizationChecker, [ "@security.authorization_checker" ]]

    app.security.product_boundless_access:
        class: AppBundle\Service\Security\ProductBoundlessAccess
        calls:
            - [setAuthorizationChecker, [ "@security.authorization_checker" ]]

    app.security.product_vending_group_boundless_access:
        class: AppBundle\Service\Security\ProductVendingGroupBoundlessAccess
        calls:
            - [setAuthorizationChecker, [ "@security.authorization_checker" ]]

    app.security.customer_boundless_access:
        class: AppBundle\Service\Security\CustomerBoundlessAccess
        calls:
            - [setAuthorizationChecker, [ "@security.authorization_checker" ]]

    app.security.student_boundless_access:
        class: AppBundle\Service\Security\StudentBoundlessAccess
        calls:
            - [setAuthorizationChecker, [ "@security.authorization_checker" ]]

    app.security.purchase_boundless_access:
        class: AppBundle\Service\Security\PurchaseBoundlessAccess
        calls:
            - [setAuthorizationChecker, [ "@security.authorization_checker" ]]

    app.security.purchase_service_boundless_access:
        class: AppBundle\Service\Security\PurchaseServiceBoundlessAccess
        calls:
            - [setAuthorizationChecker, [ "@security.authorization_checker" ]]

    app.security.payment_receipt_boundless_access:
        class: AppBundle\Service\Security\PaymentReceiptBoundlessAccess
        calls:
            - [setAuthorizationChecker, [ "@security.authorization_checker" ]]

    # Sync

    app.sync.utility.checksum:
        class: AppBundle\Service\Sync\Utility\Checksum

    app.sync.sync_data_validator:
        class: AppBundle\Service\Sync\SyncDataValidator
        calls:
            - [setManager, [ "@doctrine.orm.entity_manager" ]]
            - [setValidator, [ "@validator" ]]
            - [setChecksum, [ "@app.sync.utility.checksum" ]]

    app.sync.sync_data_handler:
        class: AppBundle\Service\Sync\SyncDataHandler
        calls:
            - [setManager, [ "@doctrine.orm.entity_manager" ]]
            - [setLogger, [ "@logger" ]]
        tags:
            - { name: monolog.logger, channel: sync }

    app.sync.sync_data_builder:
        class: AppBundle\Service\Sync\SyncDataBuilder
        calls:
            - [setChecksum, [ "@app.sync.utility.checksum" ]]

    app.sync.sync_data_recorder:
        class: AppBundle\Service\Sync\SyncDataRecorder
        calls:
            - [setManager, [ "@doctrine.orm.entity_manager" ]]

    app.sync.security.password_encoder:
        class: AppBundle\Service\Sync\Security\PasswordEncoder

    app.sync.security.authentication:
        class: AppBundle\Service\Sync\Security\Authentication
        calls:
            - [setPasswordEncoder, [ "@app.sync.security.password_encoder" ]]

    # Reports

    app.report.builder:
        class: AppBundle\Service\Report\ReportBuilder
        calls:
            - [setManager, [ "@doctrine.orm.entity_manager" ]]

    app.report.excel.accounting:
        class: AppBundle\Service\Report\ReportExcelAccounting
        calls:
            - [setRootDirectory, [ "%kernel.root_dir%" ]]
            - [setPhpExcel, [ "@phpexcel" ]]

    app.report.excel.accounting_logistics:
        class: AppBundle\Service\Report\ReportExcelAccountingLogistics
        calls:
            - [setRootDirectory, [ "%kernel.root_dir%" ]]
            - [setPhpExcel, [ "@phpexcel" ]]

    app.report.excel.logistics:
        class: AppBundle\Service\Report\ReportExcelLogistics
        calls:
            - [setRootDirectory, [ "%kernel.root_dir%" ]]
            - [setPhpExcel, [ "@phpexcel" ]]

    app.report.mailer:
        class: AppBundle\Service\Report\ReportMailer
        calls:
            - [setManager, [ "@doctrine.orm.entity_manager" ]]
            - [setMailerShortcut, [ "@app.common.mailer_shortcut" ]]
            - [setEmailParameters, [ "%emails%" ]]

    # Website

    app.website.feedback_mailer:
        class: AppBundle\Service\Website\FeedbackMailer
        calls:
            - [setMailerShortcut, [ "@app.common.mailer_shortcut" ]]
            - [setTranslator, [ "@translator" ]]
            - [setTemplating, [ "@templating" ]]
            - [setEmailParameters, [ "%emails%" ]]
