# app/config/common/twig.yml
twig:
    globals:
        developers: "%developers%"

        setting_boundless_access:               "@app.security.setting_boundless_access"
        employee_boundless_access:              "@app.security.employee_boundless_access"
        region_boundless_access:                "@app.security.region_boundless_access"
        settlement_boundless_access:            "@app.security.settlement_boundless_access"
        school_boundless_access:                "@app.security.school_boundless_access"
        vending_machine_boundless_access:       "@app.security.vending_machine_boundless_access"
        vending_machine_event_boundless_access: "@app.security.vending_machine_event_boundless_access"
        vending_machine_load_boundless_access:  "@app.security.vending_machine_load_boundless_access"
        nfc_tag_boundless_access:               "@app.security.nfc_tag_boundless_access"
        supplier_boundless_access:              "@app.security.supplier_boundless_access"
        product_boundless_access:               "@app.security.product_boundless_access"
        product_vending_group_boundless_access: "@app.security.product_vending_group_boundless_access"
        customer_boundless_access:              "@app.security.customer_boundless_access"
        student_boundless_access:               "@app.security.student_boundless_access"
        purchase_boundless_access:              "@app.security.purchase_boundless_access"
        purchase_service_boundless_access:      "@app.security.purchase_service_boundless_access"
        payment_receipt_boundless_access:       "@app.security.payment_receipt_boundless_access"
        transaction_boundless_access:           "@app.security.transaction_boundless_access"
