<?php

namespace AppBundle\Entity\Website\Feedback\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FeedbackSupplierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeedbackSupplierRepository extends EntityRepository
{
}
