<?php

namespace AppBundle\Entity\Supplier\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SupplierImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SupplierImageRepository extends EntityRepository
{
}
