<?php

namespace AppBundle\Entity\VendingMachine\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * VendingMachineEventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VendingMachineEventRepository extends EntityRepository
{
}
